### ISSUE TITLE
Leaving the project is not possible

### ISSUE THREAD

**Issue by matthijskooijman** [PlanBCode/hypha#287]
When you try to leave a hypha project, a goodby e-mail is sent, but then the user is not deactivated. The PHP error log shows:

```
PHP Fatal error:  Uncaught Error: Call to undefined function dropUser() in /home/giplt/web/koppelting.org/public_html/system/datatypes/settings.php:146\nStack trace:\n#0 /home/giplt/web/koppelting.org/public_html/system/core/events.php(183): settingspage->quit('')\n#1 /home/giplt/web/koppelting.org/public_html/system/core/events.php(263): processCommand('settingsQuit', '')\n#2 /home/giplt/web/koppelting.org/public_html/index.php(106): executePostedCommand()\n#3 {main}\n  thrown in /home/giplt/web/koppelting.org/public_html/system/datatypes/settings.php on line 146, referer: http://koppelting.org/settings/quit
```

Looking at the code, it seems the quit handling calls a function `dropUser()`, which does not exist (and did not exist in the first version committed to git already).

**Comment by tammoterhark** [comment]
See #261

**Comment by matthijskooijman** [comment]
Ah, indeed, this is a duplicate of #261.
