### ISSUE TITLE
PHP 7.4 shows white screen, no log entries

### ISSUE THREAD

**Issue by tammoterhark** [PlanBCode/hypha#336]
Working local: Windows10, XAMPP with PHP 7.4.8

Most recent version of meetjestad.net as well as universiteitamersfoort.nl show completely white screen, no errors. No entries in acces log or error log of Apache.

**Comment by matthijskooijman** [comment]
No errors in the error log is weird, that would suggest that the script runs successfully, but no output is generated somehow. Or that errors do not end up in the log you are looking at.

Here's two things to try:
 1. Open the "network" tab of the browser developer tools and then refresh the page to see the response status (typically 200 for success or 500 for error). If you're unsure where to look, just post a screenshot of the list.
 2. Create a file called `DEBUG` in the root of your hypha directory. This should cause errors (like those normally printed to the apache error log) to be (also) sent to the browser. Just in case this helps, but it's also generally useful while developing. Note that this does not work for (syntax) errors in index.php, since index.php needs to run and configure the error output before it takes effect.

**Comment by tammoterhark** [comment]
![image](https://user-images.githubusercontent.com/6483317/90156631-f68fca80-dd8c-11ea-9d6f-728bdda38cde.png)

**Comment by tammoterhark** [comment]
Debug shows:

Fatal error: Access level to DOMWrap\Traits\ManipulationTrait::inputAsNodeList() must be public (as in class DOMWrap\Traits\TraversalTrait) in E:\universiteitamersfoort.nl\system\php-dom-wrapper\Element.php on line 75

**Comment by tammoterhark** [comment]
But there is no line 75, there are only 23 lines.... :-(

**Comment by tammoterhark** [comment]
This was in an old version of Hypha.

The newest verseion shows the same virgin white page, but with a debug file in the root of localhost.meetjestad.net it shows:

Warning: rename(data/hypha.stats.tmp_for_writing,data/hypha.stats): Access is denied. (code: 5) in E:\meetjestad.net\system\core\database.php on line 751

Fatal error: Uncaught RuntimeException: Failed to write to file data/hypha.stats, rename from data/hypha.stats.tmp_for_writing failed: rename(data/hypha.stats.tmp_for_writing,data/hypha.stats): Access is denied. (code: 5) in E:\meetjestad.net\system\core\database.php:754 Stack trace: #0 E:\meetjestad.net\system\core\database.php(800): HyphaFile->write('{"1580058863":5...') #1 E:\meetjestad.net\system\core\base.php(795): HyphaFile->writeAndUnlock('{"1580058863":5...') #2 E:\meetjestad.net\system\core\pages.php(262): hypha_incrementStats(1588951878) #3 E:\meetjestad.net\index.php(125): loadPage(Object(RequestContext)) #4 {main} thrown in E:\meetjestad.net\system\core\database.php on line 754

**Comment by matthijskooijman** [comment]
Warning: rename(data/hypha.stats.tmp_for_writing,data/hypha.stats): Access is denied. (code: 5)

That is the same error you showed earlier this week, apparently the process running PHP has no write access to the `data/` directory and/or files inside.

Googling for XAMPP and PHP write access does not give me much useful info (a lot of people seem to say "it should just work", but apparently it does not). Maybe you can edit the properties of these files and/or the entire data directory to assign the correct write permissions for the user that PHP runs as, as suggested [here](https://stackoverflow.com/questions/9349469/changing-php-write-permissions-in-xampp-on-windows-7)? I'm always confused by the Windows file permissions dialogs, so I don't have any ready-made instructions on how this would work...

**Comment by tammoterhark** [comment]
Tried, but no luck. Once I am in De War again AND (1 OF devs) is there, please help. Cannot proceed.

**Comment by matthijskooijman** [comment]
More investigation shows that the permissions on the files are fine, and it can write to files without problems. However, the error occurs because files are written to a temporary filename and then renamed over the original filename (to prevent problems with full disks, see #265). It turns out that Windows refuses to replace any files that are still open, even if it is only the current process that has the file open. And since the file is locked to prevent concurrent writes, it has to be opened (and other processes might also have it open if they are waiting for a lock).

Weirdly enough, unlinking the old file while it is open *does* work, but subsequently renaming it does not (it's as if having the file open keeps it visible, at least to the current process, maybe only actually unlinking it when the file is closed?).

For now, I've added a workaround to @tammoterhark's hypha install that closes (and implicitly unlocks) the original file before the rename, but that opens a race condition so is not a proper solution.

Maybe a solution could be to use a separate .lock file after all, rather than locking the file itself (or locking the temp file maybe), so the original file remains unlocked and is not open. This might still cause problems when other processes have the file openend (even if momentarily to read it). This could be solved by unlinking the original before the rename, but that would again introduce a race condition where a short amount of time the file does not exist, causing reads to fail). An alternative would be to use a separate .lock file and also use shared locks for reading on that file, which should ensure that no process is reading the file while it is being renamed.

This needs some more thought...

**Comment by matthijskooijman** [comment]
One problem with separate .lock files is the question: Who will remove them when done, and can that be done atomically (probably not, I'm afraid)?
